### C:\Program Files\Git\etc\profile.d
alias ls='ls -F --color=auto --show-control-chars'
alias ll='ls -l'
alias gst='git status'
alias gl='git log'
alias gp='git push'
alias gpr='git pull --rebase'
alias gcm='git commit'
alias gsw='git switch'
alias gf='git fetch'
alias ga='git add'
alias gau='git add -u'